NUMPY

In [4]:
import numpy as np


In [5]:
a1 = np.array([1, 2, 3])
print(a1)

[1 2 3]


In [6]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a2[0]

array([1, 2, 3])

In [8]:
a2[1]

array([4, 5, 6])

In [9]:
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
a2[1, 2]

6

In [11]:
a3[1, 0, 1]

8

In [12]:
av = np.empty([4,3])
av

array([[4.65722672e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [13]:
az = np.zeros([3,5])        #Ceros
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
ao = np.ones([3,5])         #Unos
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
af = np.full([3,5],8)   #El número que quieras
af

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [16]:
ai = np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [18]:
ar = np.arange(1,10,2)      #Inicio - final - pasos
ar

array([1, 3, 5, 7, 9])

In [19]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

In [20]:
al = np.linspace(1,100,20)      #Inicio, final, cantidad de números requeridos
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [21]:
aran = np.random.random([2,3])
aran

array([[0.99407852, 0.88149102, 0.03470213],
       [0.74023945, 0.95956134, 0.65255235]])

In [22]:
aran.ndim       #Dimensión

2

In [23]:
aran.shape      # Filas y columnas

(2, 3)

In [24]:
aran.size       # Número de elemnentos

6

In [25]:
aran.dtype      # Tipo de datos

dtype('float64')

In [26]:
at = np.array(['Hola','mundo'])     # Tienen que ser del mismo tipo de datos, no se puede mezclar números y letras
at

array(['Hola', 'mundo'], dtype='<U5')

In [27]:
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [28]:
al.dtype

dtype('float64')

In [29]:
al.astype('i')      # Convierte los datos a enteros

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [30]:
aran

array([[0.99407852, 0.88149102, 0.03470213],
       [0.74023945, 0.95956134, 0.65255235]])

In [31]:
np.sort(aran, axis=1)       # ordenda 1 = filas y 0 = columnas

array([[0.03470213, 0.88149102, 0.99407852],
       [0.65255235, 0.74023945, 0.95956134]])

In [32]:
print(np.max(aran))     # Muestra el máximo

0.9940785206138175


In [33]:
arr = np.array([2,4,5,0,6,1,-3])
arr

array([ 2,  4,  5,  0,  6,  1, -3])

In [34]:
np.min(arr)

-3

In [35]:
np.abs(arr)

array([2, 4, 5, 0, 6, 1, 3])

In [36]:
np.std(arr)

2.8996833043120622

In [37]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [38]:
np.NaN          # Dato falso, vacio

nan

In [39]:
np.infty        # Dato infinito

inf

In [40]:
arr

array([ 2,  4,  5,  0,  6,  1, -3])

In [41]:
for x in arr:
    print(x)

2
4
5
0
6
1
-3


In [42]:
for i in range(len(arr)):
    print(i, arr[i])

0 2
1 4
2 5
3 0
4 6
5 1
6 -3


In [43]:
aran

array([[0.99407852, 0.88149102, 0.03470213],
       [0.74023945, 0.95956134, 0.65255235]])

In [44]:
for x in aran:
    for y in x:
        print(y)

0.9940785206138175
0.8814910155861891
0.03470213308358583
0.7402394472937678
0.9595613441151716
0.6525523541346274


In [45]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
for x in a3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
for x in np.nditer(a3):         # nditer te hace lo anterior directamente
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [48]:
for pos, x in np.ndenumerate(a3):        # Te hace lo mismo pero te muestra su posición
    print(pos, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [49]:
np.where(a3 > 5)

(array([0, 1, 1, 1, 1, 1, 1]),
 array([1, 0, 0, 0, 1, 1, 1]),
 array([2, 0, 1, 2, 0, 1, 2]))

In [50]:
a1

array([1, 2, 3])

In [51]:
a1[a1>1]

array([2, 3])

In [52]:
a2[:2,1:]

array([[2, 3],
       [5, 6]])

In [53]:
a3[:3,1:,:1]

array([[[ 4]],

       [[10]]])

In [54]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

arr = np.concatenate((arr1, arr2), axis=0)      # Junta los dos arrays
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:

arr = np.concatenate((arr1, arr2), axis=1)      # Junta los dos arrays con dos filas
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [56]:
arrs= np.stack((arr1, arr2), axis=1)            # Junta los dos arrays apilando
arrs

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [57]:
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [58]:
splitted = np.array_split(arr, 3, axis=1)
splitted

for s in splitted:
    print(s)

[[1 2]
 [4 5]]
[[ 3  7]
 [ 6 10]]
[[ 8  9]
 [11 12]]


In [59]:
splitted = np.array_split(arr, 3, axis=0)
splitted

for s in splitted:
    print(s)

[[1 2 3 7 8 9]]
[[ 4  5  6 10 11 12]]
[]


In [60]:
arr = np.array([1,2, np.NaN,7,4,0])     # Al estar vacio (NaN) la suma no la ejecuta
print(arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [61]:
for pos in range(len(arr)):         # Se sustituye el valor NaN por lo que queramos, en este caso 0
    if np.isnan(arr[pos]):
        arr[pos] = 0
print(arr)

[1. 2. 0. 7. 4. 0.]


In [62]:
lista = [x for x in arr]            # Genera lista con bucle anidado
lista

[1.0, 2.0, 0.0, 7.0, 4.0, 0.0]

In [63]:
lista = [x/2 for x in arr]
lista

[0.5, 1.0, 0.0, 3.5, 2.0, 0.0]

In [64]:
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)


array([1., 2., 0., 7., 4., 0.])

In [65]:
np.isnan(arr)       # Te dice si es nulo o tiene valor

array([False, False, False, False, False, False])

In [66]:
arr[np.logical_not(np.isnan(arr))]      # Se elimina valor nulos

array([1., 2., 0., 7., 4., 0.])

In [67]:
arr[np.isfinite(arr)]

array([1., 2., 0., 7., 4., 0.])

In [68]:
copia = arr.copy()         # copia el arr
vista = arr.view()         # muestra el último

print('original:', arr)
print('copia:', copia)
print('vista:', vista)

arr[0] = 67


print('original:', arr)
print('copia:', copia)
print('vista:', vista)

original: [1. 2. 0. 7. 4. 0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [1. 2. 0. 7. 4. 0.]
original: [67.  2.  0.  7.  4.  0.]
copia: [1. 2. 0. 7. 4. 0.]
vista: [67.  2.  0.  7.  4.  0.]


In [82]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = arr1.reshape([2,3,2])
print(arr2)
arr3 = arr2.reshape(12)
arr3

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,1,1],[2,2,2]])

print(a+b)
print(a*b)

[[2 3 4]
 [6 7 8]]
[[ 1  2  3]
 [ 8 10 12]]


In [87]:
# 1x + 2y = 1
# 3x + 5y = 2

a = np.array([[1,2],[3,5]])
b = np.array([1,2])

c = np.linalg.solve(a,b)
c

array([-1.,  1.])